# Generated by Django 4.2.5 on 2023-09-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full_name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='Phone number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='No subject', max_length=100, verbose_name='Title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('interval', models.PositiveSmallIntegerField(choices=[(1, 'once in a day'), (7, 'once in a week'), (31, 'once in a month')], verbose_name='interval')),
                ('status', models.CharField(choices=[('created', 'created'), ('started', 'started'), ('finished', 'finished')], default='created', verbose_name='status')),
                ('clients', models.ManyToManyField(to='mailing.client', verbose_name='Clients')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
