# Generated by Django 4.2.5 on 2023-09-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_client_owner_mailingsettings_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Message'),
        ),
    ]
